apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-microservice-k8s
spec:
  selector:
    matchLabels:
      app: user-microservice-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: user-microservice-k8s
    spec:
      containers:
        - name: user-microservice-k8s
          image: sachcha99/ctse-user-microservice-k8s:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      tolerations:
        - key: "key"
          operator: "Exists"
          effect: "NoSchedule"